In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

dataset = pd.read_csv("playTennis.csv")
# print(data)
feature_cols = dataset.columns[1:5]
print(feature_cols)

for label in feature_cols:
    dataset[label]=LabelEncoder().fit_transform(dataset[label])

data = dataset.drop(['PlayTennis'],axis=1)
data = np.array(data.drop(['Day'],axis=1))
target = np.array(dataset['PlayTennis'])
print(data)
print(target)

X_train , X_test, y_train, y_test = train_test_split(data,target,test_size=0.2,random_state=40)

id3 = DecisionTreeClassifier(criterion='entropy')
id3.fit(X_train,y_train)
y_pred = id3.predict(X_test)
print("Actual value :",y_test)
print("Predicted value :",y_pred)
print("Accuracy: ",metrics.accuracy_score(y_test,y_pred))

new_example = np.array(['Hot','High','Weak'])
encoded = LabelEncoder().fit_transform(new_example)
test = encoded.reshape(1,-1)
test_predict = id3.predict(test)
print("Input given:",new_example)
print("Predicted output :",test_predict)

Index(['Temperature', 'Humidity', 'Wind', 'PlayTennis'], dtype='object')
[[1 0 1]
 [1 0 0]
 [1 0 1]
 [2 0 1]
 [0 1 1]
 [0 1 0]
 [0 1 0]
 [2 0 1]
 [0 1 1]
 [2 1 1]
 [2 1 0]
 [2 0 0]
 [1 1 1]
 [2 0 0]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Actual value : [0 0 1]
Predicted value : [1 1 1]
Accuracy:  0.3333333333333333
Input given: ['Hot' 'High' 'Weak']
Predicted output : [1]
