In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

In [2]:
dataset = pd.read_csv("PlayTennis.csv")
print(dataset)

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No


In [3]:
all_cols=dataset.columns
print(type(all_cols))

<class 'pandas.core.indexes.base.Index'>


In [4]:
feature_cols=all_cols[1:5]
print(feature_cols)

Index(['Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')


In [5]:
#feature encoding
for label in dataset.columns:
    dataset[label]=LabelEncoder().fit_transform(dataset[label])
    print(dataset[label])

0     2
1     2
2     0
3     1
4     1
5     1
6     0
7     2
8     2
9     1
10    2
11    0
12    0
13    1
Name: Outlook, dtype: int32
0     1
1     1
2     1
3     2
4     0
5     0
6     0
7     2
8     0
9     2
10    2
11    2
12    1
13    2
Name: Temperature, dtype: int32
0     0
1     0
2     0
3     0
4     1
5     1
6     1
7     0
8     1
9     1
10    1
11    0
12    1
13    0
Name: Humidity, dtype: int32
0     1
1     0
2     1
3     1
4     1
5     0
6     0
7     1
8     1
9     1
10    0
11    0
12    1
13    0
Name: Wind, dtype: int32
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play Tennis, dtype: int32


In [6]:
#formatting into numpy array
data=dataset.drop(['Play Tennis'],axis=1)
print(data)

target=np.array(dataset['Play Tennis'])
print(target)

    Outlook  Temperature  Humidity  Wind
0         2            1         0     1
1         2            1         0     0
2         0            1         0     1
3         1            2         0     1
4         1            0         1     1
5         1            0         1     0
6         0            0         1     0
7         2            2         0     1
8         2            0         1     1
9         1            2         1     1
10        2            2         1     0
11        0            2         0     0
12        0            1         1     1
13        1            2         0     0
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [7]:
#splitting the dataset
# X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.3)
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.3,shuffle=False,random_state=42)
print(y_test)

[1 1 1 1 0]


In [8]:
#Train Desicion tree classifier
id3=DecisionTreeClassifier(criterion="entropy")
id3=id3.fit(X_train,y_train)
print(id3)

DecisionTreeClassifier(criterion='entropy')


In [9]:
#predict the response for test dataset
y_pred=id3.predict(X_test)
print("Actual output:",y_test)
print("predicted output:",y_pred)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Actual output: [1 1 1 1 0]
predicted output: [1 1 1 1 0]
Accuracy: 1.0


In [10]:
#classify a new example
New_example =np.array(['Sunny','Hot','High','Weak'])
le=LabelEncoder()
encoded=le.fit_transform(New_example)
print(encoded)
encoded=encoded.reshape(1,-1)
print(encoded)
#le1-LabelEncoder()
new_pred=id3.predict(encoded)
#en=le1.fit_transform(new_pred)
#decoded=le1.nverse_transform(en)
print(new_pred)

[2 1 0 3]
[[2 1 0 3]]
[0]


c:\Users\NIREEKSH SHETTY\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
